option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy" False)

if (ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if (CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};-extra-arg=-std=c++17")
    else ()
        message(SEND_ERROR "clang-tidy not found")
    endif ()
endif ()
